#!/bin/bash
set -euo pipefail


install_location=<install_location>
dc_media="docker compose -f ${install_location}/media/docker-compose.yaml"
dc_starrs="docker compose -f ${install_location}/starrs/docker-compose.yaml"
dc_network="docker compose -f ${install_location}/network/docker-compose.yaml"
dc_management="docker compose -f ${install_location}/management/docker-compose.yaml"
option=${1:-"help"}
compose_file=${2:-""}
container=${3:-""}
not_running=$(printf "\e[34m\e[0m\e[33mNot Running\e[0m\n")
my_domain="<my_domain>"
traefik="<traefik>"
help() {
   echo "Fly-Hi Media"
   echo
   echo "Usage: fly-hi [help|option] [compose-file]"
   echo "options:"
   echo "help        displays this help message"
   echo "restart     restarts Fly-Hi services"
   echo "stop        stops all Fly-Hi services"
   echo "start       starts Fly-Hi services"
   echo "update      updates Fly-Hi services"
   echo "destroy     destroy Fly-Hi services but preserve container data"
   echo "uninstall   completely remove all containers and their data from the system"
   echo "ip          checks if the VPN is working as expected"
   echo "ports       shows all ports currently used and opened by docker containers"
   echo "links       shows links to access your services"
   echo "links-all   shows all links, including non running services"
}

send_message_in_green() {
    echo -e $(printf "\e[32m$1\e[0m")
}

send_message_in_red() {
    echo -e $(printf "\e[31m$1\e[0m")
    exit 255
}
send_message_in_blue() {
    echo -e "\e[34m$1\e[0m"
}


if [[ $option == "help" ]]; then
    help
    exit 0
fi
if [[ $option == "ports" ]]; then
        docker ps --format '{{.Names}}\t{{.Ports}}'
fi


if [[ $option == "vpn" ]]; then
bash ${install_location}/*install.sh
fi
if [[ $option == "noip" ]]; then
sudo /usr/local/bin/noip2 -S
fi

if [[ $option == "restart" ]]; then
    if [[ -z "$compose_file" ]]; then
        $dc_management stop && $dc_management up -d
        $dc_network stop && $dc_network up -d
        $dc_media stop && $dc_media up -d
        $dc_starrs stop && $dc_starrs up -d
    else
        case $compose_file in
            "media")
                $dc_media stop && $dc_media up -d
                ;;
            "starrs")
                $dc_starrs stop && $dc_starrs rm -f qbittorrent && $dc_starrs rm -f qbittorrentpub && $dc_starrs up -d
                ;;
            "network")
                $dc_network stop && $dc_network up -d
                ;;
            "management")
                $dc_management stop && $dc_management up -d
                ;;
            "$compose_file")
                docker restart $compose_file
                ;;
            *)
                send_message_in_red "Invalid compose file specified. Please choose one of: media, starrs, network, management."
                ;;
        esac
    fi
    echo "Fly-Hi is starting. Wait 1 min until all the services are up and running..."
    exit 0
fi

if [[ $option == "stop" ]]; then
    if [[ -z "$compose_file" ]]; then
        $dc_media stop
        $dc_starrs stop
        $dc_network stop
        $dc_management stop
    else
        case $compose_file in

            "media")
                $dc_media stop
                ;;
            "starrs")
                $dc_starrs stop
                ;;
            "network")
                $dc_network stop
                ;;
            "management")
                $dc_management stop
                ;;
            "$compose_file")
                docker stop $compose_file
                ;;
            *)
                send_message_in_red "Invalid compose file specified. Please choose one of: media, starrs, network, management."
                ;;
        esac
    fi
    exit 0
fi

if [[ $option == "start" ]]; then
    if [[ -z "$compose_file" ]]; then
        $dc_management up -d
        $dc_network up -d
        $dc_media up -d
        $dc_starrs up -d
    else
        case $compose_file in
            "media")
                $dc_media up -d
                ;;
            "starrs")
                $dc_starrs stop qbittorrent qbittorrentpub && $dc_starrs rm -f qbittorrent && $dc_starrs rm -f qbittorrentpub && $dc_starrs up -d
                ;;
            "network")
                $dc_network up -d
                ;;
            "management")
                $dc_management up -d
                ;;
            "$compose_file")
                docker start $compose_file
                ;;
            *)
                send_message_in_red "Invalid compose file specified. Please choose one of: media, starrs, network, management."
                ;;
        esac
    fi
    send_message_in_green "Fly-Hi is up and running!"
    exit 0
fi

if [[ $option == "update" ]]; then
    if [[ -z "$compose_file" ]]; then
        $dc_media pull && $dc_media up -d
        $dc_starrs pull && $dc_starrs up -d
        $dc_network pull && $dc_network up -d
        $dc_management pull && $dc_management up -d
    else
        case $compose_file in
            "media")
                $dc_media pull && $dc_media up -d
                ;;
            "starrs")
                $dc_starrs pull && $dc_starrs up -d
                ;;
            "network")
                $dc_network pull && $dc_network up -d
                ;;
            "management")
                $dc_management pull && $dc_management up -d
                ;;
            *)
                send_message_in_red "Invalid compose file specified. Please choose one of: media, starrs, network, management."
                ;;
        esac
    fi
    echo "Fly-Hi is updating. Wait 1 min until all the services are up and running..."
    exit 0
fi

if [[ $option == "destroy" ]]; then
    if [[ -z "$compose_file" ]]; then
        $dc_media down --remove-orphans
        $dc_starrs down --remove-orphans
        $dc_network down --remove-orphans
        $dc_management down --remove-orphans
    else
        case $compose_file in
            "media")
                $dc_media down --remove-orphans
                ;;
            "starrs")
                $dc_starrs down --remove-orphans
                ;;
            "network")
                $dc_network down --remove-orphans
                ;;
            "management")
                $dc_management down --remove-orphans
                ;;
            "$compose_file")
                docker stop $compose_file && docker rm $compose_file
                ;;
            *)
                send_message_in_red "Invalid compose file specified. Please choose one of: media, starrs, network, management or a container name."
                ;;
        esac
    fi
    exit 0
fi

if [[ $option == "ip" ]]; then
    echo "Getting your qBittorrent IP..."
    qbittorrent_ip=$(docker exec qbittorrent sh -c "curl -s ifconfig.me");
    echo "$qbittorrent_ip"
    echo "Your country in qBittorrent is $($dc_starrs exec -it qbittorrent sh -c 'curl -s https://am.i.mullvad.net/country')"
    echo "Your city in qBittorrent is $($dc_starrs exec -it qbittorrent sh -c 'curl -s curl https://am.i.mullvad.net/city')"
    echo
    echo "Getting your IP..."
    your_ip=$(curl -s ifconfig.me)
    echo "$your_ip"
    echo "Your local IP country is $(curl -s https://am.i.mullvad.net/country)"
    echo "Your local IP city is $(curl -s curl https://am.i.mullvad.net/city)"
    echo
    if [[ $qbittorrent_ip == $your_ip ]]; then
           send_message_in_red "Your IPs are the same! qBittorrent is NOT working! ⚠️"
   else
           send_message_in_green "Your IPs are different. qBittorrent is working as expected! ✅ "
    fi
fi


if [[ $option == "uninstall" ]]; then
    read -p "This will uninstall your fly-hi script and remove all container data including the ones not installed with this script, proceed? [n,Y]:" uninstall
    uninstall=${uninstall:-"y"}
    if [[ "$uninstall" =~ [yY] ]]; then
        read -p "Would you like to also delete container persistant data from your original install location? [N,y]:" delete_persistant
        uninstall=${delete_persistant:-"n"}
        read -p "Would you like to also uninstall and purge your docker installation? [N,y]:" uninstall_docker
        uninstall_docker=${uninstall_docker:-"n"}
        fly-hi destroy media || true
        fly-hi destroy starrs || true
        fly-hi destroy network || true
        fly-hi destroy management || true
        docker network rm fly-hi || true
        sudo docker system prune -a || true
        if [[ $option == "delete_persistant" ]]; then
            sudo rm -r ${install_location} || true
            send_message_in_green "You successefully delete your persistant container data!"
        fi
        if [[ "$uninstall_docker" =~ [yY] ]]; then
            sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin docker* || true
            sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin || true
            sudo umount /var/lib/docker/ || true
            sudo rm -rf /var/lib/docker /etc/docker || true
            sudo rm /etc/apparmor.d/docker || true
            sudo groupdel docker || true
            sudo rm -rf /var/run/docker.sock || true
            sudo rm -rf /usr/bin/docker-compose || true
            sudo rm -rf /usr/local/bin/docker-compose || true
            sudo rm -rf /var/lib/containerd || true
            sudo rm /usr/local/lib/docker/cli-plugins/docker-compose || true
            send_message_in_green "You are ready for a fresh install of docker!"
        else
            send_message_in_green "You successefully uninstalled your fly-hi-media and docker!"
        fi
            sudo rm /usr/local/bin/fly-hi
    fi
fi



links() {
    host_ip=$(hostname -I | awk '{ print $1 }')
 print_link() {
    service_name=$1
    port=$(docker port $service_name 2>/dev/null | awk '{ print $3 }' | head -1 | sed 's/0.0.0.0://' || true)

    if [[ -n "$port" ]]; then
        if [[ $traefik =~ [yY] ]]; then
        printf "\e[34m%-15s\e[0m: \e[34m%s://%s:%s\e[0m \e[33m%s\e[0m\n" "${service_name^}" "http" "$host_ip" "$port"  "https://$1.$my_domain"
        else
        printf "\e[34m%-15s\e[0m: \e[34m%s://%s:%s\e[0m \e[33m%s\e[0m\n" "${service_name^}" "http" "$host_ip" "$port"
        fi
    else
        printf "\e[34m%-15s\e[0m: \e[33mNot Running\e[0m\n" "${service_name^}"
    fi
}

    echo
    echo -e $(printf "\e[34m===== MANAGEMENT =====\e[0m")
    print_link "homarr"
    print_link "heimdall"
    send_message_in_blue "Cockpit        : http://$host_ip:9090"
    print_link "portainer"
    print_link "netdata"
    print_link "uptime-kuma"
    print_link "glances"
    print_link "scrutiny"
    print_link "phpmyadmin"
    print_link "pgadmin"
    print_link "whoami"
    print_link "dozzle"
    graylog=$(cat ${install_location}/management/docker-compose.yaml | grep WEB-UI | awk '{ print $2 }' | awk -F":" '{ print $1 }') || true
    if [[ -z "$graylog" ]]; then
    send_message_in_blue "Graylog        : $not_running"
    else
        if [[ $traefik =~ [yY] ]]; then
        send_message_in_blue "Graylog        : http://$host_ip:$graylog $(printf "\e[33m https://wgeasy.$my_domain \e[0m")"
        else
        send_message_in_blue "Graylog        : http://$host_ip:$graylog"
        fi
    fi
    print_link "ntfy"
    print_link "vaultwarden"
    print_link "homeassistant"
    print_link "maybe"
    echo

    echo -e $(printf "\e[34m===== NETWORK =====\e[0m")
    send_message_in_blue "Traefik        : http://$host_ip:8880 $(printf "\e[33m https://traefik.$my_domain \e[0m")" #traefik#
    wgeasy=$(cat ${install_location}/network/docker-compose.yaml | grep WEB | awk '{ print $2 }' | awk -F":" '{ print $1 }') || true
    if [[ -z "$wgeasy" ]]; then
    send_message_in_blue "WG-Easy        : $not_running"
    else
        if [[ $traefik =~ [yY] ]]; then
        send_message_in_blue "WG-Easy        : http://$host_ip:$wgeasy $(printf "\e[33mhttps://wgeasy.$my_domain \e[0m")"
        else
        send_message_in_blue "WG-Easy        : http://$host_ip:$wgeasy"
        fi
    fi
    print_link "speedtest"
    print_link "flaresolverr"
    echo

    echo -e $(printf "\e[34m===== MEDIA =====\e[0m")
    print_link "jellyfin"
    print_link "emby"
    plex=$(cat ${install_location}/media/docker-compose.yaml | grep webUI | awk -F":" '{ print $2 }' | awk '{ print $1 }') || true
    if [[ -z "$plex" ]]; then
    send_message_in_blue "Plex           : $not_running"
    else
        if [[ $traefik =~ [yY] ]]; then
        send_message_in_blue "Plex           : http://$host_ip:$plex $(printf "\e[33mhttps://plex.$my_domain \e[0m")"
        else
        send_message_in_blue "Plex           : http://$host_ip:$plex"
        fi
    fi
    print_link "jellyseerr"
    print_link "overseerr"
    print_link "ombi"
    print_link "airsonic"
    print_link "navidrome"
    print_link "immich_server"
    print_link "photoprism"
    print_link "calibre"
    print_link "calibre_web"
    print_link "audiobookshelf"
    print_link "readeck"
    print_link "linkding"
    print_link "linkwarden"
    print_link "stirlingpdf"
    print_link "nextcloud"
    print_link "filebrowser"
    print_link "joplin"
    print_link "todo"
    print_link "vikunja"
    print_link "freshrss"
    print_link "mealie"
    print_link "privatebin"
    print_link "pingvinshare"
    print_link "snapdrop"
    echo

    echo -e $(printf "\e[34m===== STARRS =====\e[0m")
    qbittorrent=$(cat ${install_location}/network/docker-compose.yaml | grep qbittorrentport | grep -Eo '[0-9]{1,4}' | head -1) || true
    if [[ -z "$qbittorrent" ]]; then
    send_message_in_blue "Qbittorrent    : $not_running"
    else
        if [[ $traefik =~ [yY] ]]; then
        send_message_in_blue "Qbittorrent    : http://$host_ip:$qbittorrent $(printf "\e[33mhttps://qbittorrent.$my_domain \e[0m")"
        else
        send_message_in_blue "Qbittorrent    : http://$host_ip:$qbittorrent"
        fi
    fi
    qbittorrentpub=$(cat ${install_location}/network/docker-compose.yaml | grep qbittorrentpubport | grep -Eo '[0-9]{1,4}' | head -1) || true
    if [[ -z "$qbittorrentpub" ]]; then
    send_message_in_blue "Qbittorrentpub : $not_running"
    else
        if [[ $traefik =~ [yY] ]]; then
        send_message_in_blue "Qbittorrentpub : http://$host_ip:$qbittorrentpub $(printf "\e[33mhttps://qbittorrentpub.$my_domain \e[0m")"
        else
        send_message_in_blue "Qbittorrentpub : http://$host_ip:$qbittorrentpub"
        fi
    fi
    print_link "radarr"
    print_link "sonarr"
    print_link "lidarr"
    print_link "readarr"
    print_link "prowlarr"
    print_link "bazarr"
    print_link "pinchflat"
    print_link "ytdl-sub"
    echo
    send_message_in_green "Use 'fly-hi help' to see how to use the script"
    echo
    send_message_in_green "To start up Tailscale run 'sudo tailscale up' " #tailscale#
    echo
}
if [[ $option == "links-all" ]]; then
links
fi
if [[ $option == "links" ]]; then
links | grep -v "Not Running"
fi

